package dambi.accessingmongoumeak.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import dambi.accessingmongoumeak.model.Langilea.LangileaRepository;
import dambi.accessingmongoumeak.model.Partida.PartidaRepository;

@RestController // This means that this class is a Controller baina @Controller bakarrik
				// jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/inkestak") // This means URL's start with /demo (after Application path)
public class InkestaController {
	@Autowired // This means to get the bean called umeaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private PartidaRepository partidaRepository;
	private LangileaRepository langileaRepository;

}