package dambi.accessingmongoumeak.controller;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import dambi.accessingmongoumeak.model.Jokoa;
import dambi.accessingmongoumeak.model.Inkesta.Inkesta;
import dambi.accessingmongoumeak.model.Inkesta.InkestaRepository;


@RestController // This means that this class is a Controller baina @Controller bakarrik
				// jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/inkestak") // This means URL's start with /demo (after Application path)
public class InkestaController {
	@Autowired // This means to get the bean called umeaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private InkestaRepository inkestaRepository;

	@PostMapping(path = "/inkestaBerria") // Map ONLY POST Requests
	public @ResponseBody String addInkestaBerria(@RequestParam String erabiltzailea,@RequestParam int jokoaID,
			@RequestParam String jokoarenIzena,@RequestParam String lehenengoGaldera,@RequestParam String bigarrenGaldera,@RequestParam String hirugarrenGaldera,@RequestParam String laugarrenGaldera) {
				
		Jokoa jokoa = new Jokoa(jokoaID, jokoarenIzena);

		List<String> galderenErantzunak = new ArrayList<>();
		galderenErantzunak.add(lehenengoGaldera);
		galderenErantzunak.add(bigarrenGaldera);
		galderenErantzunak.add(hirugarrenGaldera);
		galderenErantzunak.add(laugarrenGaldera);

		Inkesta inkesta = new Inkesta(erabiltzailea, jokoa, galderenErantzunak);
		inkestaRepository.save(inkesta);
		return "Saved";
	}

	@GetMapping(path = "/jokoarenInkesta")
	public @ResponseBody Inkesta getJokoarenBatazBestekoa(String erabiltzailea,String jokoarenIzena) {
		return inkestaRepository.findByErabiltzaileaJokoa(erabiltzailea, jokoarenIzena);
	}

	@DeleteMapping(path = "/inkestaEzabatu/{erabiltzailea}/{jokoarenIzena}")
	public String deleteInkesta(String erabiltzailea,String jokoarenIzena) {
		try {
			return inkestaRepository.delete(erabiltzailea, jokoarenIzena);
		} catch (Exception ex) {
			System.out.println("Errorea inkesta ezabatzerakoan. ");
			return "Errorea egon da";

		}
	}
}