package dambi.accessingmongoumeak.controller;

import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import javax.validation.Valid;

import org.bson.types.Decimal128;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import dambi.accessingmongoumeak.model.Jokoa;
import dambi.accessingmongoumeak.model.Langilea.Langilea;
import dambi.accessingmongoumeak.model.Langilea.LangileaRepository;
import dambi.accessingmongoumeak.model.Partida.Partida;
import dambi.accessingmongoumeak.model.Partida.PartidaRepository;

@RestController // This means that this class is a Controller baina @Controller bakarrik
				// jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/partidak") // This means URL's start with /demo (after Application path)
public class PartidaController {
	@Autowired // This means to get the bean called umeaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private PartidaRepository partidaRepository;

	@PostMapping(path = "/partidaBerria") // Map ONLY POST Requests
	public @ResponseBody String addPartidaBerria(@RequestParam int _id, @RequestParam float puntuazioa,
			@RequestParam String data, @RequestParam int idJokoa, @RequestParam String izenaJokoa,
			@RequestParam String erabiltzaileIzena ) {

		Jokoa jokoa = new Jokoa(idJokoa, izenaJokoa);
		Langilea langilea = new Langilea(erabiltzaileIzena);

		Partida partida = new Partida();
		partida.setId(_id);
		partida.setErabiltzailea(langilea);
		partida.setPuntuazioa(puntuazioa);
		partida.setData(data);
		partida.setJokoa(jokoa);
		partidaRepository.partidaBerria(partida);
		return "Saved";
	}

}