package dambi.accessingrelationaldata.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import dambi.accessingrelationaldata.model.Langilea;
import dambi.accessingrelationaldata.respository.LangileaRepository;

@Service
public class LangileaServices {

    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private LangileaRepository langileaRepository;

    public Langilea saveLangilea(Langilea langilea) {
        return langileaRepository.save(langilea);
    }

    public Iterable<Langilea> getAllLangileak() {
        // This returns a JSON or XML with the users
        return langileaRepository.findAll();
    }

    public void deleteLangilea(String erabiltzailea) {
        langileaRepository.deleteById(erabiltzailea);
    }
}
